BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Auction_items" (
	"item_ID"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("item_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Bids" (
	"bid_ID"	INTEGER NOT NULL UNIQUE,
	"amount"	INTEGER NOT NULL,
	"item_ID"	INTEGER,
	PRIMARY KEY("bid_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Shop_items" (
	"item_ID"	INTEGER NOT NULL UNIQUE,
	"price"	INTEGER NOT NULL,
	PRIMARY KEY("item_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Users" (
	"user_ID"	INTEGER NOT NULL UNIQUE,
	"email"	TEXT NOT NULL,
	PRIMARY KEY("user_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Purchases" (
	"item_ID"	INTEGER NOT NULL,
	"user_ID"	INTEGER NOT NULL,
	FOREIGN KEY("item_ID") REFERENCES "Shop_items"("item_ID")
);
CREATE TABLE IF NOT EXISTS "Actions" (
	"action_ID"	INTEGER NOT NULL UNIQUE,
	"target"	INTEGER NOT NULL,
	PRIMARY KEY("action_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Transactions" (
	"transaction_ID"	INTEGER NOT NULL UNIQUE,
	"amount"	REAL NOT NULL,
	"action_ID"	INTEGER,
	PRIMARY KEY("transaction_ID" AUTOINCREMENT)
);
COMMIT;
